// <auto-generated />
using System;
using Avantibit.Optimizely.CustomSettings.Persistence.EfCore.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avantibit.Optimizely.CustomSettings.Migrations
{
    [DbContext(typeof(CustomSettingsDbContext))]
    [Migration("20260301200324_AddSettingsVersionTable")]
    partial class AddSettingsVersionTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Avantibit.Optimizely.CustomSettings.Persistence.Abstractions.SettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SettingsType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SettingsType", "SiteId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("Settings_Composite")
                        .HasFilter("[SiteId] IS NOT NULL AND [LanguageCode] IS NOT NULL");

                    b.ToTable("CustomSettings", (string)null);
                });

            modelBuilder.Entity("Avantibit.Optimizely.CustomSettings.Persistence.Abstractions.SettingsVersionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CustomSettingsVersion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Version = 0L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
